# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
		conf.env['ENABLE_ZMQ'] = conf.check(mandatory=False, lib='zmq', define_name='Have_ZMQ', uselib='ZMQ')
		
		conf.env.append_value("LINKFLAGS", ["-lzmq"])
		conf.env.append_value("LIB", ["zmq"])

def build(bld):
    module = bld.create_ns3_module('opengym', ['core'])
    module.source = [
        'model/opengym.cc',
        'helper/opengym-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('opengym')
    module_test.source = [
        'test/opengym-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'opengym'
    headers.source = [
        'model/opengym.h',
        'helper/opengym-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

